# Generated by Django 4.1.4 on 2023-01-28 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='client_id',
        ),
    ]
