# Generated by Django 4.1.4 on 2023-01-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
