# Generated by Django 4.1.4 on 2023-01-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='account_type',
            field=models.CharField(choices=[('R', 'Regular'), ('G', 'Gold'), ('P', 'Platinum'), ('D', 'Diimond')], default='R', max_length=1),
        ),
    ]
